package profile

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// GeneratePlatformCache writes {dataDir}/cache/platform.sh.
// Output format must match core/platform.sh's _dotfiles_write_platform_cache.
func GeneratePlatformCache(dataDir string, info *PlatformInfo) error {
	cacheDir := filepath.Join(dataDir, "cache")
	if err := os.MkdirAll(cacheDir, 0755); err != nil {
		return err
	}

	wsl := ""
	if info.WSL {
		wsl = "true"
	}
	container := ""
	if info.Container {
		container = "true"
	}

	var b strings.Builder
	b.WriteString("# Generated by dotfiles — do not edit\n")
	b.WriteString("# Re-generate: dotfiles cache rebuild\n")
	fmt.Fprintf(&b, "DOTFILES_OS=\"%s\"\n", info.OS)
	fmt.Fprintf(&b, "DOTFILES_ARCH=\"%s\"\n", info.Arch)
	fmt.Fprintf(&b, "DOTFILES_WSL=\"%s\"\n", wsl)
	fmt.Fprintf(&b, "DOTFILES_DISTRO=\"%s\"\n", info.Distro)
	fmt.Fprintf(&b, "DOTFILES_DISTRO_VERSION=\"%s\"\n", info.DistroVersion)
	fmt.Fprintf(&b, "DOTFILES_PKG_MANAGER=\"%s\"\n", info.PkgManager)
	fmt.Fprintf(&b, "DOTFILES_CONTAINER=\"%s\"\n", container)
	fmt.Fprintf(&b, "HOMEBREW_PREFIX=\"%s\"\n", info.HomebrewPrefix)
	fmt.Fprintf(&b, "MACOS_VERSION=\"%s\"\n", info.MacOSVersion)

	return os.WriteFile(filepath.Join(cacheDir, "platform.sh"), []byte(b.String()), 0644)
}

// GenerateProfileCache writes {dataDir}/cache/profile.sh.
// Output format must match setup/generate-cache.sh exactly.
func GenerateProfileCache(dataDir string, profilePath string, p *Profile) error {
	cacheDir := filepath.Join(dataDir, "cache")
	if err := os.MkdirAll(cacheDir, 0755); err != nil {
		return err
	}

	enabled := p.EnabledModules()
	sort.Strings(enabled)
	disabled := p.DisabledSections()
	sort.Strings(disabled)

	var b strings.Builder
	b.WriteString("# Generated by dotfiles — do not edit\n")
	fmt.Fprintf(&b, "# Source: %s\n", profilePath)
	fmt.Fprintf(&b, "# Generated: %s\n", time.Now().Format(time.RFC3339))
	b.WriteString("\n")
	fmt.Fprintf(&b, "DOTFILES_PROFILE_SOURCE=\"%s\"\n", profilePath)

	// Enabled modules
	fmt.Fprintf(&b, "DOTFILES_ENABLED_MODULES=(%s)\n", strings.Join(enabled, " "))

	// Disabled sections
	fmt.Fprintf(&b, "DOTFILES_DISABLED_SECTIONS=(%s)\n", strings.Join(disabled, " "))

	b.WriteString("\n")
	b.WriteString("# Modes — first triggered wins, checked in order\n")

	// Mode names (stable order)
	modeNames := make([]string, 0, len(p.Modes))
	for name := range p.Modes {
		modeNames = append(modeNames, name)
	}
	sort.Strings(modeNames)

	fmt.Fprintf(&b, "DOTFILES_MODE_NAMES=(%s)\n", strings.Join(modeNames, " "))

	// Per-mode variables
	for _, name := range modeNames {
		mode := p.Modes[name]
		modeType := mode.Type
		if modeType == "" {
			modeType = "include"
		}
		fmt.Fprintf(&b, "DOTFILES_MODE_%s_TYPE=%s\n", name, modeType)
		fmt.Fprintf(&b, "DOTFILES_MODE_%s_TRIGGERS=(%s)\n", name, strings.Join(mode.EnvTriggers, " "))
		fmt.Fprintf(&b, "DOTFILES_MODE_%s_MODULES=(%s)\n", name, strings.Join(mode.IncludeModules, " "))
		fmt.Fprintf(&b, "DOTFILES_MODE_%s_NEVER_LOAD=(%s)\n", name, strings.Join(mode.NeverLoad, " "))
	}

	return os.WriteFile(filepath.Join(cacheDir, "profile.sh"), []byte(b.String()), 0644)
}

// ClearCache removes the {dataDir}/cache/ directory entirely.
func ClearCache(dataDir string) error {
	return os.RemoveAll(filepath.Join(dataDir, "cache"))
}
